### PR TITLE
Add hello-world exercise

### PR DESCRIPTION
**Pull request by bergjohan**
# Prerequisites

## Linux/Ubuntu 18.10
\# apt-get install git
\# apt-get install cmake
\# apt-get install nasm
\# apt-get install gcc-multilib

## Mac
\# brew install git
\# brew install cmake
\# brew install nasm

## Windows
Install Git (https://git-scm.com/download/win)
Install Visual Studio (https://visualstudio.microsoft.com/)
Install NASM (https://www.nasm.us/)

# Running the tests

## Linux/Mac
$ cd x86/exercises/hello-world/
$ mkdir build
$ cd build
$ cmake ..
$ make

## Windows
See https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017
Build as Debug x86

Ref: #1

### CODE REVIEW

**Comment by sshine** [comment]
Two pieces of feedback:

- I think it's called `apt install <program>` now, rather than `apt-get install`. (Both should work, though.)
- I think the test process should be made simpler than `mkdir build; ...`.

---

Ubuntu 17.10 (which I'm running) comes with a too old CMake version:

    ~/exercism/x86-assembly/exercises/hello-world/build$ cmake ..
    CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
      CMake 3.11 or higher is required.  You are running version 3.9.1


    -- Configuring incomplete, errors occurred!

I'm not able to test this with an updated version until Monday.

Feel free to continue to merge without me and I'll give further feedback Monday.

**Comment by sshine** [comment]
I see that CMakeLists.txt contains:

    cmake_minimum_required(VERSION 3.11)

I also see changing this to 3.9 produces an error because `FetchContent_Declare` is first supported in 3.11. This macro-function-thingy is used to drag in https://github.com/ThrowTheSwitch/Unity.git -- it doesn't seem like a good idea that each time an Exercism user tests a newly downloaded solution, we make them fetch a 3rd party unit testing resource.

Could installing this `Unity` library instead be part of the track bootstrap instructions?

**Comment by bergjohan** [comment]
@sshine Thanks for the feedback, I really appreciate it!

> I think it's called apt install <program> now, rather than apt-get install. (Both should work, though.)

Yeah, you are right. This was not meant as a complete installation guide, just something to list the prerequisites to get started.

> I think the test process should be made simpler than mkdir build; ....

I chose to use CMake for cross-platform support. This is the way to generate Makefiles and I don't think this could be made any simpler. Note that you only have to do this once, after that the make command is enough to run the tests.

> it doesn't seem like a good idea that each time an Exercism user tests a newly downloaded solution, we make them fetch a 3rd party unit testing resource.

Why do you think this is bad? This way the student don't have to worry about the installation of the unit test framework. I could have done it like the C track and commited the Unity files in the repo, but I felt it was unnecessary to duplicate the files in every exercise.
But if the required CMake version is too high and students have to manually build it, I think that's a problem.

**I pushed a new version where I use a single header test framework (Catch2) that is commited to the repo. You should be able to try it out with your current CMake version.**

**Comment by sshine** [comment]
OK, so now `cmake` is working excellently! But `make` says something about a missing header:

```
build$ make
[ 25%] Building CXX object CMakeFiles/hello-world.dir/main.cpp.o
In file included from /home/simon/exercism/x86-assembly/exercises/hello-world/catch.hpp:391:0,
                 from /home/simon/exercism/x86-assembly/exercises/hello-world/main.cpp:2:
/usr/include/c++/7/iosfwd:38:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/hello-world.dir/build.make:62: recipe for target 'CMakeFiles/hello-world.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/hello-world.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hello-world.dir/all' failed
make[1]: *** [CMakeFiles/hello-world.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

This is because my `bits/c++config.h` is in

    /usr/include/x86_64-linux-gnu/c++/7/

and not in

    /usr/include/c++/7/

I'm not sure about the "iosfwd" part of the path.

And I'm not sure where to add an `-I...` line to progress (even though a better fix is warranted).

And I'm not sure why there is C++ stuff failing; is this because the compilation pipeline is made from C++ tools, or because the x86 code somehow gets wrapped in C++ runtime in order to compile it?

**Comment by bergjohan** [comment]
@sshine Thanks for testing! Because I switched to a C++ test framework, you will need to install the g++-multilib package to compile for 32-bit.
It might be overkill to use such a feature-rich testing framework for these simple tests. Maybe it's better to find something lighter and go back to C, I don't know.

**Comment by sshine** [comment]
I wrote:
> Could installing this Unity library instead be part of the track bootstrap instructions?

I'm still a proponent of this idea if you think this testing framework is superior.

But it should be possible to install without also needing to manually compile its dependencies from source, or risk some compilation error because of mismatching version numbers compared to those of the dependencies on the system. I.e., it should preferrably be in a package manager (if not the operating system's, then the programming language's preferred package tool).

**Comment by sshine** [comment]
> Maybe it's better to find something lighter and go back to C, I don't know.

I'd assume so. I don't know what feature differences there are or how advanced tests you intend to write.

For the Haskell track we use Hspec, which is a very fine library. If this were my personal project I might add the Tasty framework around it and the Hedgehog property-based test framework that tries to beat QuickCheck, but on the other hand: Mainly I as the test-writer stands to benefit; the student will just run the test suite. So fewer dependencies means shorter download / compile time and fewer sources of problems.

**Comment by bergjohan** [comment]
I think it's hard to find a C/C++ test framework that's easy to install on all platforms prior to downloading the exercise. That's why I would prefer a single header library, which makes it alot easier.
The C track is including all three source files from Unity when the exercise is downloaded, see 
https://github.com/exercism/c/tree/master/exercises/hello-world/test/vendor. What do you think about that?

**Comment by bergjohan** [comment]
C/C++ doesn't really have any package tools like other languages. I think there are some testing frameworks in the OS package manager. That makes it easy to install on Linux, but not on Windows.

**Comment by bergjohan** [comment]
Because the tests are so simple, I guess it's even possible to write a simple test framework myself like: 
http://eradman.com/posts/tdd-in-c.html

**Comment by sshine** [comment]
> That's why I would prefer a single header library
> The C track is including all three source files from Unity when the exercise is downloaded
> What do you think about that?

The SML track, which I maintain, does too: 

https://github.com/exercism/sml/blob/master/exercises/hello-world/testlib.sml

I don't like that we do it, but since there aren't even any standardized test frameworks for SML, and there is no package manager to distribute it, this is the least complicated choice. I've had to modify the test framework once since it didn't support comparing reals allowing for small imprecisions, and then the copies of the test framework for the other exercises become out of sync.

> Because the tests are so simple, I guess it's even possible to write a simple test framework myself

Either that or do as the C track does with `vendor/`. There are pros and cons.

I might personally prefer not having to write my own test library if there is one that fits the bill.

You can keep the reference version in the track repo but outside of any specific exercise directory.

If you choose to write your own, I would keep a reference version for the latest version in the track repo but outside of any specific exercise directory. That way, when you realize it lacks a feature, you can update it centrally and push the newest version down. It's okay that exercises use old versions of the test suite as long as it supports the exercise's current tests.

The downside of not doing that is that I can't remember which exercise contains the version of testlib.sml that is one feature ahead. And I might forget and write another feature in another copy of it.

But you can be free of that problem altogether if you're happy with an existing test framework. :-)

**Comment by bergjohan** [comment]
@sshine I decided to go with Unity and include the source files in the exercise like the C track. Like you said, it doesn't require as much work, and it's got everything I need.

By the way, I ran some tests on Windows Visual Studio to see if I could get it running without CMake. It is possible, but it requires quite a few manual steps, like setting up a custom build tool and specifying the command line for NASM e.g. `"C:\NASM\nasm" -f win32 --gprefix _`. I think it will be too hard and error prone and it's better to stick with CMake. With CMake, all you need is to do is open the directory which contains the CMakeLists.txt file and run the application.

**I pushed a new version with the changes I mentioned, could you verify that it's working for you?**

**Comment by sshine** [comment]
Hi, sorry for the response time. I'll check later today!

**Comment by bergjohan** [comment]
Thanks, no worries, I'm just glad you wanna help out :)

**Comment by bergjohan** [comment]
@sshine Hm, I just read that macOS Mojave "is the final version of macOS to support 32-bit application software", https://en.m.wikipedia.org/wiki/MacOS_Mojave. Maybe we need to switch to x86-64 assembly?
The problem with that is that Microsoft is using a different calling convention for x86-64, e.g. passing arguments in different registers.
What's the best solution for that? Force Windows users to use WSL or mingw? Somehow mark solutions that are written on Windows to allow mentors to identify if they need MSVC to compile?

**Comment by sshine** [comment]
Hi @bergjohan 

I think switching to x86-64 sounds reasonable on the account that modern processors use this architecture.

If Microsoft uses a different calling convention for x86-64, this means that a unit testing framework that supports both Microsoft's assembler and something else cannot unconditionally place parameters to computations or expect in which register the result of a computation lies, right?

I don't know what the best approach is here. Picking a single calling convention sounds like the easier / realistic choice. I would personally favor whatever is the most popular non-commercial standard; doing a quick search, it seems to me that this is [cdecl](https://en.wikipedia.org/wiki/X86_calling_conventions#cdecl)?

**Comment by bergjohan** [comment]
> If Microsoft uses a different calling convention for x86-64, this means that a unit testing framework that supports both Microsoft's assembler and something else cannot unconditionally place parameters to computations or expect in which register the result of a computation lies, right?

This means that if the exercise is compiled with Microsoft's C compiler, the RCX register will be used for the first function argument instead of the RDI register which is used on Linux. The students assembly code will be different based on which compiler is used.

> I don't know what the best approach is here. Picking a single calling convention sounds like the easier / realistic choice. I would personally favor whatever is the most popular non-commercial standard; doing a quick search, it seems to me that this is cdecl?

The cdecl calling convention is used by default in 32-bit applications. For 64-bit applications there are only two different calling conventions. One is the "System V AMD64 ABI" which is used by Linux/MacOS and the other one is the "Microsoft x64 calling convention".

I've been thinking, and I think the best way is to pick a single calling convention like you say, and stay clear of the MSVC compiler. Students on Windows will have to use Mingw-w64 or Windows Subsystem for Linux (WSL).

@sshine I've pushed a new version without CMake. The only prerequisites are a C compiler, make and nasm. Would you mind trying out the new version to see if it's working for you?

**Comment by sshine** [comment]
I'll do that in my next break. :)

**Comment by bergjohan** [comment]
Great! Thank you :)

**Comment by sshine** [comment]
It's working great on Linux. I like how simple the toolchain is now.

Perhaps we should ask someone on Windows if this is working?

**Comment by bergjohan** [comment]
@sshine Cool! I got it working last night using Mingw-w64 on Windows, I'll try it with WSL tonight.
What do you think, is it ready to be merged after that and used as a template for other exercises?

**Comment by sshine** [comment]
@bergjohan: I think so.

**Comment by sshine** [comment]
You may want to squash and merge this PR. :-)

**Comment by bergjohan** [comment]
Cool! I'll try to get the merge done tonight. Yeah, I'll clean it up before merging :)

**Pull request merged**
